### ISSUE TITLE
Ability to mark an area in the video with the report pertains to

### ISSUE THREAD

**Issue by moahmed** [batpad/crveillance-reports#2]
a red square or circle would do.

this should he marked on the key frame so please viewing the report know where to look

**Comment by batpad** [comment]
@moahmed rough outline of what would be needed here:

The `VideoReport` model would need either a "box" or "coordinates" field for either a bounding box or point coordinates on the image. Then, on the frontend, we need some way for the user to click / mark out area of the video, grab the coordinates, send them alongwith the POST request, and save them on the backend.

I agree this will be nice to have, but is a bit of work - let me know if this might be interesting for you to dig into - I can help you get setup with the project, etc. - otherwise I will probably put this on hold for now in favour of other more immediate issues.

Thanks for the issue!

**Comment by moahmed** [comment]
I think simple solution would be stick the image from the frame into a img tag and just let them click
and draw a circle on it ... save the radius and x and y with the report ...

re draw the circle later 

but sure I could also look into doing that, need understand how to work with the code base

**Comment by moahmed** [comment]
simple make img with circle and transparent background ... 

put both images one on top of the other and change with of top image

**Comment by batpad** [comment]
This was implemented in https://github.com/batpad/crveillance-reports/pull/8 - thanks so much for the code @moahmed !
